"""
JISC logging utility fiunctions

Functions to help logging used across modules.
"""

import argparse
import inspect
import logging
import os
from importlib import metadata


def setup_logging(args: argparse.Namespace, logfilename: str) -> None:
    """Prepare logging.

    Args:
        args (argparse.Namespace): Runtime arguments.
        logfilename (str): Name of logfile.
    """
    calling_file_name = os.path.basename(inspect.stack()[1].filename)
    level = logging.INFO
    if args.debug:
        level = logging.DEBUG
    log_full_path = os.path.join(os.getcwd(), logfilename)
    logging.basicConfig(
        filename=log_full_path,
        filemode="w",
        format="%(asctime)s - %(levelname)s - %(message)s",
        level=level,
    )
    logging.info(
        "This log file was generated by %s from %s v.%s",
        calling_file_name,
        __package__,
        metadata.version("jisc_wrangler"),
    )
    if args.dry_run:
        logging.info("Executing a DRY RUN. No files will be copied.")

    print("Logging to the current directory at:\n%s", log_full_path)
