"""
JISC logging utility fiunctions

Functions to help logging used across modules.
"""

import os
import logging
from jisc_wrangler import constants
import pkg_resources
import inspect

def setup_logging(args, logfilename):
    """
    Prepare logging.
    """
    calling_file_name = os.path.basename(inspect.stack()[1].filename)
    level = logging.INFO
    if (args.debug):
        level = logging.DEBUG
    log_full_path = os.path.join(os.getcwd(), logfilename)
    logging.basicConfig(filename=log_full_path, filemode='w',
                        format='%(asctime)s - %(levelname)s - %(message)s',
                        level=level)
    logging.info(
        "This log file was generated by "
        f"{calling_file_name} from {__package__} "
        f"v.{pkg_resources.get_distribution(__package__).version}"
    )
    if args.dry_run:
        logging.info("Executing a DRY RUN. No files will be copied.")

    print(f"Logging to the current directory at:\n{log_full_path}")